### ISSUE TITLE
Add Merge sort algorithm in C language

### ISSUE THREAD

**Issue by subin-shk** [Saloni6111/DSA_Problems#324]
I would like to add merge sort algorithm in C language. 
Please assign this task to me

**Comment by Shreyaww** [comment]
Can you please assign this issue to me as this would be my first contribution in hacktoberfest

**Comment by subin-shk** [comment]
I'm sorry shreya but i need this.

**Comment by subin-shk** [comment]
can you also add hacktoberfest label
